[package]
name = "bevy-rtest"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.0"
bevy_rapier2d = { version = "0.27.0", features = ["simd-stable", "debug-render-2d"] }
bevy_prototype_lyon = "=0.12.0"
rand = "0.8.5"